@startuml
Interface Comparable
Interface Space {
    +add(Queue)
    +remove(Queue)
    +display()
}
Abstract Creature
Class Embattler
Class Huluwa
Class Laoyeye
Class Shejing
Class Xiejing
Class Louluo
Class Position
Class PosCoord
Class Queue
Class Sorter
Class Space2D
Enum DIRECTION
Enum ORIENTATION
Enum FORMATION
Enum COLOR
Enum SENIORITY
Enum SORT_TYPE

Creature <|-- Huluwa
Creature <|-- Laoyeye
Creature <|-- Xiejing
Creature <|-- Shejing
Creature <|-- Louluo
Creature o--> Position
Position o--> Creature
Space <|.. Space2D
Comparable <|.. Huluwa
Comparable <-- Sorter
Sorter --> Queue
Queue *--> Position
Queue o--> Creature
Position o--> PosCoord
Embattler --> Queue
Embattler --> ORIENTATION
Embattler --> PosCoord
Space --> Queue

FORMATION <-- Embattler
COLOR <--* Huluwa
SENIORITY <--* Huluwa
SORT_TYPE <-- Sorter
DIRECTION <-- ORIENTATION
ORIENTATION <-- PosCoord

@enduml
